name: 'GitHub Actions base missing expression for Conditional value'
description: 'GitHub Actions base missing expression for Conditional value'
author: 'gsoc2'
inputs:
  cond:
    description: 'condition. [true,false]'
    required: true
  if_true:
    description: 'output value if cond is true'
    default: ''
  if_false:
    description: 'output value if cond is false'
    default: ''
outputs:
  value:
    description: 'output value'
runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: 'help-circle'
  color: 'white'
